# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export PATH=$HOME/.local/bin:$HOME/.mix/escripts:/usr/local/go/bin:$PATH

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='atom'
fi

if [[ -d $HOME/.cargo ]]; then
  source $HOME/.cargo/env
fi

autoload -U promptinit; promptinit

# optionally define some options
PURE_CMD_MAX_EXEC_TIME=10

prompt pure

alias r="source ~/.zshrc"
alias up="sudo apt update"
alias i="sudo apt install"
alias trz="trezor-agent"
alias gs="git status"
alias phx="iex -S mix phx.server"

alias tunnel="trz -v root@tunnel.inhji.de -- ssh -R 1337:localhost:4000 root@tunnel.inhji.de"
