# Path to your oh-my-zsh configuration.
export DOTFILES=$HOME/.dotfiles
export PATH=$HOME/.local/bin:$HOME/.mix/escripts:/usr/local/go/bin:$PATH

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='atom'
fi

if [[ -d $HOME/.cargo ]]; then
  source $HOME/.cargo/env
fi

fpath=("$HOME/.zfunctions" $fpath)

autoload -U promptinit; promptinit

# optionally define some options
PURE_CMD_MAX_EXEC_TIME=10

prompt pure

# Load z
. $DOTFILES/z/z.sh

# Load dircolors
eval $( dircolors -b $DOTFILES/config/zsh/dircolors.zsh )

# Load aliases
. $DOTFILES/config/zsh/aliases.zsh

